INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resis, retreat, cardNumberInCollection, collection_id, type_id, stage_id)
VALUES
(80, 'Abra', 'Psi Pokémon', 'Psyshock', '10', 'Psychic', 'None', '1 Colorless', 43, 1, 5, 1),
(100, 'Alakazam', 'Psi Pokémon', 'Confuse Ray', '30', 'Psychic', 'None', '3 Colorless', 1, 1, 5, 3),
(70, 'Arcanine', 'Legendary Pokémon', 'Flamethrower', '50', 'Water', 'None', '3 Colorless', 23, 1, 1, 2),
(60, 'Caterpie', 'Worm Pokémon', 'String Shot', '10', 'Fire', 'None', '1 Colorless', 45, 1, 3, 1),
(90, 'Beedrill', 'Poison Bee Pokémon', 'Twineedle', '30x', 'Fire', 'None', '2 Colorless', 17, 1, 3, 3),
(70, 'Clefairy', 'Fairy Pokémon', 'Sing', '0', 'Steel', 'None', '1 Colorless', 5, 1, 10, 1),
(100, 'Clefable', 'Fairy Pokémon', 'Metronome', '—', 'Steel', 'None', '2 Colorless', 1, 2, 10, 2),
(80, 'Cubone', 'Lonely Pokémon', 'Bone Club', '20', 'Grass', 'None', '1 Colorless', 50, 2, 6, 1),
(90, 'Marowak', 'Bone Keeper Pokémon', 'Bonemerang', '30x', 'Grass', 'None', '2 Colorless', 39, 2, 6, 2),
(70, 'Diglett', 'Mole Pokémon', 'Dig', '10', 'Grass', 'None', '1 Colorless', 35, 1, 6, 1),
(90, 'Dugtrio', 'Mole Pokémon', 'Earthquake', '70', 'Grass', 'None', '2 Colorless', 19, 1, 6, 2),
(80, 'Doduo', 'Twin Bird Pokémon', 'Fury Attack', '10x', 'Electric', 'None', '1 Colorless', 48, 1, 10, 1),
(100, 'Dodrio', 'Triple Bird Pokémon', 'Rage', '10+', 'Electric', 'None', '2 Colorless', 34, 1, 10, 2),
(70, 'Eevee', 'Evolution Pokémon', 'Tackle', '10', 'Fighting', 'None', '1 Colorless', 55, 2, 10, 1),
(90, 'Flareon', 'Flame Pokémon', 'Flamethrower', '60', 'Water', 'None', '2 Colorless', 3, 2, 1, 2),
(90, 'Jolteon', 'Lightning Pokémon', 'Pin Missile', '20x', 'Fighting', 'None', '2 Colorless', 4, 2, 4, 2),
(90, 'Vaporeon', 'Bubble Jet Pokémon', 'Water Gun', '30+', 'Electric', 'None', '2 Colorless', 12, 2, 2, 2),
(70, 'Zubat', 'Bat Pokémon', 'Leech Life', '10', 'Electric', 'None', '1 Colorless', 57, 3, 6, 1),
(80, 'Golbat', 'Bat Pokémon', 'Wing Attack', '30', 'Electric', 'None', '2 Colorless', 25, 3, 6, 2),
(100, 'Muk', 'Sludge Pokémon', 'Sludge', '30', 'Psychic', 'None', '2 Colorless', 13, 3, 5, 2),
(90, 'Hypno', 'Hypnosis Pokémon', 'Prophecy', '—', 'Psychic', 'None', '2 Colorless', 8, 3, 5, 2),
(70, 'Krabby', 'River Crab Pokémon', 'Vice Grip', '10', 'Electric', 'None', '1 Colorless', 51, 3, 2, 1),
(90, 'Kingler', 'Pincer Pokémon', 'Crabhammer', '40', 'Electric', 'None', '2 Colorless', 34, 3, 2, 2),
(80, 'Omanyte', 'Spiral Pokémon', 'Water Gun', '10+', 'Grass', 'None', '1 Colorless', 52, 3, 2, 1),
(100, 'Omastar', 'Spiral Pokémon', 'Hydro Pump', '20+', 'Grass', 'None', '2 Colorless', 26, 3, 2, 2),
(70, 'Kabuto', 'Shellfish Pokémon', 'Scratch', '10', 'Grass', 'None', '1 Colorless', 50, 3, 2, 1),
(90, 'Kabutops', 'Shellfish Pokémon', 'Slash', '30', 'Grass', 'None', '2 Colorless', 24, 3, 2, 2),
(80, 'Aerodactyl', 'Fossil Pokémon', 'Wing Attack', '30', 'Electric', 'None', '2 Colorless', 1, 3, 9, 1),
(120, 'Articuno', 'Freeze Pokémon', 'Blizzard', '50', 'Electric', 'None', '2 Colorless', 2, 3, 2, 1),
(120, 'Zapdos', 'Electric Pokémon', 'Thunderstorm', '40', 'Fighting', 'None', '3 Colorless', 15, 3, 4, 1);
