INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resis, retreat, cardNumberInCollection, collection_id, type_id, stage_id)
VALUES
(60, 'Poliwag', 'Tadpole Pokémon', 'Water Gun', '10+', 'Electric', 'None', '1 Colorless', 59, 1, 2, 1),
(90, 'Poliwhirl', 'Tadpole Pokémon', 'Amnesia', '20', 'Electric', 'None', '2 Colorless', 39, 1, 2, 2),
(100, 'Poliwrath', 'Tadpole Pokémon', 'Water Gun', '30+', 'Electric', 'None', '3 Colorless', 13, 1, 2, 3),
(70, 'Tentacool', 'Jellyfish Pokémon', 'Acid', '10', 'Electric', 'None', '1 Colorless', 48, 3, 2, 1),
(90, 'Tentacruel', 'Jellyfish Pokémon', 'Supersonic', '—', 'Electric', 'None', '2 Colorless', 43, 3, 2, 2),
(80, 'Seel', 'Sea Lion Pokémon', 'Headbutt', '10', 'Electric', 'None', '1 Colorless', 54, 1, 2, 1),
(100, 'Dewgong', 'Sea Lion Pokémon', 'Aurora Beam', '50', 'Electric', 'None', '3 Colorless', 25, 1, 2, 2),
(70, 'Horsea', 'Dragon Pokémon', 'Smokescreen', '10', 'Electric', 'None', '1 Colorless', 50, 1, 2, 1),
(90, 'Seadra', 'Dragon Pokémon', 'Water Gun', '20+', 'Electric', 'None', '2 Colorless', 22, 1, 2, 2),
(120, 'Dragonair', 'Dragon Pokémon', 'Slam', '30x', 'Ice', 'None', '2 Colorless', 18, 1, 9, 2),
(130, 'Dragonite', 'Dragon Pokémon', 'Hyper Beam', '40', 'Ice', 'None', '2 Colorless', 19, 3, 9, 3),
(70, 'Magnemite', 'Magnet Pokémon', 'Thunder Wave', '10', 'Fighting', 'None', '1 Colorless', 54, 1, 4, 1),
(90, 'Magneton', 'Magnet Pokémon', 'Selfdestruct', '80', 'Fighting', 'None', '2 Colorless', 9, 1, 4, 2),
(80, 'Voltorb', 'Ball Pokémon', 'Tackle', '10', 'Fighting', 'None', '1 Colorless', 67, 1, 4, 1),
(100, 'Electrode', 'Ball Pokémon', 'Explosion', '80', 'Fighting', 'None', '2 Colorless', 21, 1, 4, 2),
(70, 'Grimer', 'Sludge Pokémon', 'Poison Gas', '10', 'Psychic', 'None', '1 Colorless', 48, 3, 5, 1),
(90, 'Muk', 'Sludge Pokémon', 'Sludge', '30', 'Psychic', 'None', '2 Colorless', 13, 3, 5, 2),
(80, 'Koffing', 'Poison Gas Pokémon', 'Smog', '20', 'Psychic', 'None', '1 Colorless', 51, 1, 5, 1),
(100, 'Weezing', 'Poison Gas Pokémon', 'Smog', '20', 'Psychic', 'None', '2 Colorless', 29, 1, 5, 2),
(70, 'Rattata', 'Mouse Pokémon', 'Bite', '20', 'Fighting', 'None', '1 Colorless', 56, 1, 10, 1),
(90, 'Raticate', 'Mouse Pokémon', 'Super Fang', '—', 'Fighting', 'None', '2 Colorless', 40, 1, 10, 2),
(80, 'Sandshrew', 'Mouse Pokémon', 'Scratch', '20', 'Water', 'None', '1 Colorless', 60, 1, 6, 1),
(100, 'Sandslash', 'Mouse Pokémon', 'Slash', '30', 'Water', 'None', '2 Colorless', 22, 1, 6, 2),
(70, 'Nidoran♀', 'Poison Pin Pokémon', 'Scratch', '20', 'Psychic', 'None', '1 Colorless', 57, 2, 3, 1),
(90, 'Nidorina', 'Poison Pin Pokémon', 'Supersonic', '—', 'Psychic', 'None', '2 Colorless', 36, 2, 3, 2),
(100, 'Nidoqueen', 'Drill Pokémon', 'Mega Punch', '40', 'Psychic', 'None', '3 Colorless', 7, 2, 3, 3),
(70, 'Nidoran♂', 'Poison Pin Pokémon', 'Horn Hazard', '30', 'Psychic', 'None', '1 Colorless', 58, 2, 6, 1),
(90, 'Nidorino', 'Poison Pin Pokémon', 'Horn Drill', '50', 'Psychic', 'None', '2 Colorless', 37, 2, 6, 2),
(100, 'Nidoking', 'Drill Pokémon', 'Thrash', '30+', 'Psychic', 'None', '3 Colorless', 11, 2, 6, 3),
(120, 'Mewtwo', 'Genetic Pokémon', 'Psychic', '40', 'Psychic', 'None', '3 Colorless', 10, 1, 5, 1);
